contact_links:
  - name: ğŸ”“ Security Reports
    url: https://matrix.to/#/@ZilloweZ:matrix.org
    about: "Please contact me on Matrix <@ZilloweZ:matrix.org> instead of opening a public issue."
  - name: ğŸ’¡ Feature Request
    url: https://discord.com/invite/P4R7yaA3hf
    about: "Got an idea for a feature that Zoi doesn't have yet? Suggest on our Discord Server!"
  - name: ğŸ’¬ Discord Server
    url: https://discord.com/invite/P4R7yaA3hf
    about: Please ask questions and discuss here.
  - name: ğŸ’¬ Reddit Community
    url: https://reddit.com/r/Zillowe
    about: Please ask questions and discussions here, and anything related to Zillowe Foundation.
  - name: ğŸ“š Wiki
    url: https://codeberg.org/Zusty/Zoi/wiki
    about: The wiki for Zoi.
  - name: â“ Frequently Asked Questions
    url: https://codeberg.org/Zusty/Zoi/wiki/FAQ
    about: Please check if your question is mentioned here.
